[package]
name = "whisper-tun"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "whisper"
path = "src/main.rs"

[dependencies]
bytes = "1.5.0"
serde = "1.0.197"
tokio = { version = "1.36.0", features = ["full"] }
tokio-tun = "0.11.2"
