name: Build iOS Library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      run:  rustup toolchain install nightly-x86_64-apple-darwin
    - name: Install target
      run:  rustup target add aarch64-apple-ios --toolchain nightly
    - name: Build
      run:  cargo b -r --target aarch64-apple-ios --lib
